name = "sil-so"
main = "worker.js"
compatibility_date = "2025-07-05"

[observability.logs]
enabled = true

[assets]
directory = "public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "WHATPULSE_DATA"
id = "8525b2a538b3463daf10ed46309bf482"

[triggers]
crons = ["0 0 * * 1", "0 * * * *"]

[env.production]
workers_dev = false
routes = [
  "sil.so/*",
  "www.sil.so/*"
]
